import type { Job } from "types/jobs.type";


export const FAKE_JOBS: Job[] = [
    {
        id: "1",
        title: "Senior React Architect",
        company: "Nexus Corp",
        companyUrl: "https://dummyimage.com/60x60/333/fff&text=NC",
        location: "Remote",
        type: "Full-Time",
        salary: "$160,000 - $200,000",
        tags: ["React", "TypeScript", "Node.js", "AWS"],
        description:
            "As a Senior Architect, you will be responsible for defining technical strategies, mentoring team leads, and ensuring the scalability of our flagship web application. Deep expertise in performance optimization and component lifecycle management is essential.",
        requirements: [
            "Design and implement core application architecture using modern React patterns.",
            "Optimize bundle sizes and rendering performance (critical for useEffect analysis).",
            "Conduct code reviews and mentor mid-level engineers.",
            "Collaborate with backend teams on API integration (heavy emphasis on useEffect cleanup).",
        ],
        isFeatured: true,
        categoryId: 1,
    },
    {
        id: "2",
        title: "Junior UI Developer",
        company: "Creative Labs",
        companyUrl: "https://dummyimage.com/60x60/4A90E2/fff&text=CL",
        location: "New York, NY",
        type: "Full-Time",
        salary: "$60,000 - $75,000",
        tags: ["HTML", "CSS", "JavaScript", "React"],
        description:
            "Join our fast-paced design team and turn beautiful visuals into functional code. This role focuses heavily on UI implementation and styling. Some knowledge of basic hooks (like `useState` and simple `useEffect` for basic fetching) is required.",
        requirements: [
            "Translate Figma designs into reusable React components.",
            "Ensure cross-browser compatibility and responsive design.",
            "Implement basic data fetching using component lifecycle hooks.",
            "Assist in maintenance of the company's design system.",
        ],
        isFeatured: false,
        categoryId: 1,
    },
    {
        id: "3",
        title: "Contract DevOps Engineer",
        company: "CloudStream",
        companyUrl: "https://dummyimage.com/60x60/1ABC9C/fff&text=CS",
        location: "Remote",
        type: "Contract",
        salary: "$75/hr - $95/hr",
        tags: ["AWS", "Docker", "Terraform", "CI/CD"],
        description:
            "While this is primarily a DevOps role, the successful candidate will have strong experience with JavaScript build tools and deployment scripts for React apps. You'll be using React for dashboard monitoring, requiring complex data polling and synchronization effects.",
        requirements: [
            "Manage and optimize AWS infrastructure.",
            "Implement a robust CI/CD pipeline using GitHub Actions/GitLab CI.",
            "Develop monitoring dashboards using React to display real-time data.",
            "Use `useEffect` for data polling with cleanup functions.",
        ],
        isFeatured: true,
        categoryId: 4,
    },
    {
        id: "4",
        title: "Frontend Tech Lead",
        company: "E-Commerce Giant",
        companyUrl: "https://dummyimage.com/60x60/E2594A/fff&text=EG",
        location: "San Francisco, CA",
        type: "Full-Time",
        salary: "$140,000 - $170,000",
        tags: ["React", "Redux", "Testing", "Performance"],
        description:
            "This role is highly transaction-focused, requiring careful handling of asynchronous state changes, form submissions, and user interaction debouncing. Excellent opportunity to focus on advanced data fetching and error handling with `useEffect`.",
        requirements: [
            "Architect state management solutions (Redux/Zustand integration).",
            "Implement client-side form validation and submission handling.",
            "Debug and resolve complex state synchronization bugs.",
            "Ensure 100% test coverage for all application workflows.",
        ],
        isFeatured: false,
        categoryId: 1,
    },
    {
        id: "5",
        title: "Frontend Intern",
        company: "Innovative Start",
        companyUrl: "https://dummyimage.com/60x60/F5A623/fff&text=IS",
        location: "Remote",
        type: "Internship",
        salary: "$20/hr",
        tags: ["React", "CSS", "Git"],
        description:
            "Perfect for students or career changers. You will work on simple tasks that introduce you to all fundamental React concepts, including building components, managing props, and fetching static data sources.",
        requirements: [
            "Develop simple, isolated components for the landing page.",
            "Learn and apply Git best practices (branching, PRs).",
            "Practice basic data fetching with no dependencies in `useEffect`.",
        ],
        isFeatured: false,
        categoryId: 1,
    },
    {
        id: "6",
        title: "Backend API Developer",
        company: "DataFlow Systems",
        companyUrl: "https://dummyimage.com/60x60/9B59B6/fff&text=DS",
        location: "Austin, TX",
        type: "Full-Time",
        salary: "$110,000 - $135,000",
        tags: ["Node.js", "MongoDB", "REST", "Testing"],
        description:
            "While this is a backend role, a strong understanding of how frontend applications consume APIs (especially data fetching best practices and error response handling) is key. The frontend team uses React and complex `useEffect` logic, so collaboration is mandatory.",
        requirements: [
            "Design and implement new REST API endpoints.",
            "Optimize database queries for performance.",
            "Ensure robust error handling and logging for all service calls.",
        ],
        isFeatured: false,
        categoryId: 2,
    },
    {
        id: "7",
        title: "UI/UX Designer (with React skills)",
        company: "Design Forward",
        companyUrl: "https://dummyimage.com/60x60/50E3C2/000&text=DF",
        location: "Los Angeles, CA",
        type: "Full-Time",
        salary: "$90,000 - $110,000",
        tags: ["Figma", "CSS-in-JS", "React", "SaaS"],
        description:
            "This hybrid role requires both a designer's eye and a developer's grasp of React. You'll be constantly translating design logic into code, often requiring you to encapsulate side effects within performant custom hooks.",
        requirements: [
            "Maintain and expand the React Component Library.",
            "Create high-fidelity prototypes in Figma.",
            "Write clean, component-scoped CSS/styles.",
            "Develop custom hooks that handle complex side effects (e.g., click tracking, scroll listeners).",
        ],
        isFeatured: true,
        categoryId: 5,
    },
    {
        id: "8",
        title: "Part-Time Content Writer",
        company: "Marketing Pro",
        companyUrl: "https://dummyimage.com/60x60/BDC3C7/000&text=MP",
        location: "Remote",
        type: "Part-Time",
        salary: "$30/hr",
        tags: ["Writing", "SEO", "CMS"],
        description:
            "While not a coding role, this person will interact heavily with our CMS, which is built on React. They will occasionally need to understand how components fetch and display data, making them a great use case for a non-technical manager needing to add a new job via the CRUD form.",
        requirements: [
            "Produce 3-5 articles per week on industry trends.",
            "Optimize existing content for search engines.",
            "Collaborate with the frontend team to deploy content seamlessly.",
        ],
        isFeatured: false,
        categoryId: 10,
    },
    {
        id: "9",
        title: "Full Stack Engineer",
        company: "Global Connect",
        companyUrl: "https://dummyimage.com/60x60/2980B9/fff&text=GC",
        location: "London, UK",
        type: "Full-Time",
        salary: "£80,000 - £100,000",
        tags: ["React", "Python", "SQL", "Microservices"],
        description:
            "A demanding role requiring mastery of the entire stack. On the frontend, you'll manage both complex global state and local component side effects, making robust `useEffect` implementations crucial for predictable UI behavior.",
        requirements: [
            "Develop new features across the entire stack.",
            "Maintain both relational and NoSQL databases.",
            "Ensure API performance meets strict latency requirements.",
        ],
        isFeatured: true,
        categoryId: 3,
    },
    {
        id: "10",
        title: "Senior Frontend Engineer (Testing)",
        company: "Quality Assurance Co",
        companyUrl: "https://dummyimage.com/60x60/7F8C8D/fff&text=QA",
        location: "Dallas, TX",
        type: "Contract",
        salary: "$115,000 - $130,000",
        tags: ["React", "Jest", "Cypress", "TDD"],
        description:
            "This role will focus on ensuring all asynchronous operations and side effects introduced by `useEffect` are fully covered and predictable under various conditions (loading, error, success).",
        requirements: [
            "Write comprehensive unit tests (Jest) for component logic.",
            "Develop end-to-end testing scenarios (Cypress) for core workflows.",
            "Work with engineers to eliminate unnecessary side effects.",
        ],
        isFeatured: false,
        categoryId: 8,
    },
];
